apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-argocd
  name: test-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-argocd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-argocd
    spec:
      containers:
      - image: sabrisomrani/pisquare-argo:1.1
        name: pisquare-argo
        ports:
        - containerPort: 80
        resources: {}
status: {}


apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-argocd
  name: test-argocd
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ports:
  - nodePort: 31482
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-argocd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
