apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-argocd
  name: test-argocd
spec:
  ipFamilies:
  - IPv4
  ports:
  - nodePort: 31482
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-argocd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
